### ISSUE TITLE
[Bug]FaqGen return HTTP status 500

### ISSUE THREAD

**Issue by artem-astafev** [opea-project/GenAIExamples#1132]
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

GPU-AMD

### Installation method

- [X] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

opea/faqgen-latest-2c950abe79ae 

### Description

When launch FaqGen with compose abd sending the curl request to the FaQGen mega gateway service results the following errors:

`curl http://${host_ip}:8888/v1/faqgen \
   -H "Content-Type: multipart/form-data" \
   -F "messages=Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5." \
   -F "max_tokens=32" \
   -F "stream=false"
   500 Internal Server Error `

### Reproduce steps

Start service with compose, 

check mega service with: 
`curl http://${host_ip}:8888/v1/faqgen \
   -H "Content-Type: multipart/form-data" \
   -F "messages=Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5." \
   -F "max_tokens=32" \
   -F "stream=false"`
  
  get backend logs with:
  `docker compose -f compose.yaml logs faqgen-backend-server`
 

### Raw log

```shell
faqgen-backend-server  | /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_name_or_path" in Audio2TextDoc has conflict with protected namespace "model_".
faqgen-backend-server  |
faqgen-backend-server  | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
faqgen-backend-server  |   warnings.warn(
faqgen-backend-server  | [2024-11-14 07:37:00,645] [    INFO] - Base service - CORS is enabled.
faqgen-backend-server  | [2024-11-14 07:37:00,646] [    INFO] - Base service - Setting up HTTP server
faqgen-backend-server  | [2024-11-14 07:37:00,646] [    INFO] - Base service - Uvicorn server setup on port 8888
faqgen-backend-server  | INFO:     Waiting for application startup.
faqgen-backend-server  | INFO:     Application startup complete.
faqgen-backend-server  | INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
faqgen-backend-server  | [2024-11-14 07:37:00,657] [    INFO] - Base service - HTTP server setup successful
faqgen-backend-server  | INFO:     192.165.1.21:49600 - "POST /v1/faqgen HTTP/1.1" 500 Internal Server Error
faqgen-backend-server  | ERROR:    Exception in ASGI application
faqgen-backend-server  | Traceback (most recent call last):
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
faqgen-backend-server  |     result = await app(  # type: ignore[func-returns-value]
faqgen-backend-server  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
faqgen-backend-server  |     return await self.app(scope, receive, send)
faqgen-backend-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
faqgen-backend-server  |     await super().__call__(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
faqgen-backend-server  |     await self.middleware_stack(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
faqgen-backend-server  |     raise exc
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
faqgen-backend-server  |     await self.app(scope, receive, _send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
faqgen-backend-server  |     raise exc
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
faqgen-backend-server  |     await self.app(scope, receive, send_wrapper)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
faqgen-backend-server  |     await self.app(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
faqgen-backend-server  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
faqgen-backend-server  |     raise exc
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
faqgen-backend-server  |     await app(scope, receive, sender)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
faqgen-backend-server  |     await self.middleware_stack(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
faqgen-backend-server  |     await route.handle(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
faqgen-backend-server  |     await self.app(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
faqgen-backend-server  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
faqgen-backend-server  |     raise exc
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
faqgen-backend-server  |     await app(scope, receive, sender)
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
faqgen-backend-server  |     response = await f(request)
faqgen-backend-server  |                ^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
faqgen-backend-server  |     raw_response = await run_endpoint_function(
faqgen-backend-server  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
faqgen-backend-server  |     return await dependant.call(**values)
faqgen-backend-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/home/user/GenAIComps/comps/cores/mega/gateway.py", line 589, in handle_request
faqgen-backend-server  |     result_dict, runtime_graph = await self.megaservice.schedule(
faqgen-backend-server  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 106, in schedule
faqgen-backend-server  |     response, node = await done_task
faqgen-backend-server  |                      ^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 267, in execute
faqgen-backend-server  |     data = await response.json()
faqgen-backend-server  |            ^^^^^^^^^^^^^^^^^^^^^
faqgen-backend-server  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1249, in json
faqgen-backend-server  |     raise ContentTypeError(
faqgen-backend-server  | aiohttp.client_exceptions.ContentTypeError: 500, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='http://192.165.1.21:9000/v1/faqgen'
faqgen-backend-server  | INFO:     192.165.1.21:49084 - "POST /v1/faqgen HTTP/1.1" 200 OK
```

**Comment by lvliang-intel** [comment]
@artem-astafev，
This issue is fixed, right?

**Comment by artem-astafev** [comment]
> @artem-astafev， This issue is fixed, right?

Yes, the issue is fixed, FaqGen is working normally now. 

Can close this issue
