### ISSUE TITLE
[Bug] DocSum failed on ROCm CI test 

### ISSUE THREAD

**Issue by chensuyue** [opea-project/GenAIExamples#1264]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

GPU-AMD

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://github.com/opea-project/GenAIExamples/pull/1248 

### Description

DocSum failed on ROCm CI test, since the code change in this PR won't impact the functionality on ROCm. Need AMD developer help to root cause the regression.    
https://github.com/opea-project/GenAIExamples/actions/runs/12379517563/job/34569417693?pr=1248   

### Reproduce steps

Run CI test scripts. 

### Raw log

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 638, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 678, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('0.0.0.0', 7079)
```

**Comment by chensuyue** [comment]
https://github.com/opea-project/GenAIExamples/pull/1268
