### ISSUE TITLE
[Bug] GraphRAG Backend application is crashing

### ISSUE THREAD

**Issue by artem-astafev** [opea-project/GenAIExamples#1276]
### Priority

P3-Medium

### OS type

Ubuntu

### Hardware type

GPU-AMD

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://github.com/opea-project/GenAIExamples/commit/e18369ba0d7f9ab5ddc35ed6dedcf03899766902, PR https://github.com/opea-project/GenAIExamples/pull/1250/files

### Description

GraphRAG backend application(MegaService) is crushing withImportError: `cannot import name handle_message' from 'comps.cores.mega.utils (/home/user/GenAIComps/comps/cores/mega/utils.py)` error

### Reproduce steps

1. fetch GenAIExample git repo - git clone https://github.com/opea-project/GenAIExamples.git
2. go to docker_image_build - cd ./GenAIExamples/GraphRAG/docker_image_build/
3. fetch GenAIComps repo - git clone https://github.com/opea-project/GenAIComps.git
4. build images with docker compose - docker compose -f build.yaml build
5. run GraphRAG with docker compose

### Raw log

```shell
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
```

**Comment by ZailiWang** [comment]
Thanks for reporting, let me try to reproduce and analyze the issue.

**Comment by xiguiw** [comment]
@artem-astafev 

We cannot reproduce this with latest code.

This version you used was at specific point - it changes the gateway, transfer code between GenAIComps and GenAIExamples (move some code from GenAICom to GenAIExxamples).  So you must match both repos.

You version:
https://github.com/opea-project/GenAIExamples/commit/e18369ba0d7f9ab5ddc35ed6dedcf03899766902, PR https://github.com/opea-project/GenAIExamples/pull/1250/files



Would you please update you code to latest (both GenAIExamples and GenAIComp) and try again?

**Comment by lkk12014402** [comment]
kindly remind:  the tgi (text-generation-inference) image is for `intel/hpu/gaudi` https://github.com/opea-project/GenAIExamples/blob/main/GraphRAG/docker_compose/intel/hpu/gaudi/compose.yaml#L41C1-L43C37. if use other hardware, should change the tgi docker image

**Comment by artem-astafev** [comment]
> @artem-astafev
> 
> We cannot reproduce this with latest code.
> 
> This version you used was at specific point - it changes the gateway, transfer code between GenAIComps and GenAIExamples (move some code from GenAICom to GenAIExxamples). So you must match both repos.
> 
> You version: [e18369b](https://github.com/opea-project/GenAIExamples/commit/e18369ba0d7f9ab5ddc35ed6dedcf03899766902), PR https://github.com/opea-project/GenAIExamples/pull/1250/files
> 
> Would you please update you code to latest (both GenAIExamples and GenAIComp) and try again?

Thank you for the reply, I will check and let you know

**Comment by artem-astafev** [comment]
> @artem-astafev kindly remind: the tgi (text-generation-inference) image is for `intel/hpu/gaudi` https://github.com/opea-project/GenAIExamples/blob/main/GraphRAG/docker_compose/intel/hpu/gaudi/compose.yaml#L41C1-L43C37. if use other hardware, should change the tgi docker image

Thank you for the reminder, we are using pre-build TGI image for ROCm like ghcr.io/huggingface/text-generation-inference:2.3.1-rocm for TGI instances on AMD GPUs.

**Comment by artem-astafev** [comment]
Issue is no reproducing after latest updates in GenAIComp and GenAIExamples
