### ISSUE TITLE
Setting env "MEGA_SERVICE_PORT" will cause mega service failure

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIExamples#261]
Mega service port is passing via environment "MEGA_SERVICE_PORT".
```
MEGA_SERVICE_PORT = os.getenv("MEGA_SERVICE_PORT", 7778)
```

If the environment "MEGA_SERVICE_PORT" is set, variable MEGA_SERVICE_PORT will be a string type, or else, MEGA_SERVICE_PORT is a int type. The string type will cause failure of mega service:

```
Traceback (most recent call last):
  File "/home/user/codegen.py", line 43, in <module>
    chatqna.add_remote_service()
  File "/home/user/codegen.py", line 31, in add_remote_service
    self.gateway = CodeGenGateway(megaservice=self.megaservice, host="0.0.0.0", port=self.port)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/gateway.py", line 146, in __init__
    super().__init__(
  File "/home/user/GenAIComps/comps/cores/mega/gateway.py", line 35, in __init__
    self.service = MicroService(
                   ^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/micro_service.py", line 56, in __init__
    self.event_loop.run_until_complete(self._async_setup())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/micro_service.py", line 94, in _async_setup
    if not (check_ports_availability(self.host, self.port)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/utils.py", line 33, in check_ports_availability
    return all(is_port_free(h, p) for h in hosts for p in ports)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/utils.py", line 33, in <genexpr>
    return all(is_port_free(h, p) for h in hosts for p in ports)
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/utils.py", line 20, in is_port_free
    return session.connect_ex((host, port)) != 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
```

I think this issue should be fixed in all mega services.

## How to reproduce
Set the environment "MEGA_SERVICE_PORT" when starting codegen, the error will be reproduced.

```
  codegen-xeon-backend-server:
    image: opea/codegen:latest
    container_name: codegen-xeon-backend-server
    depends_on:
      - llm
    ports:
      - "7778:7778"
    environment:
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP}
      - MEGA_SERVICE_PORT= 8000
    ipc: host
    restart: always
```

**Comment by huiyan2021** [comment]
os.getenv() returns a string, could you try MEGA_SERVICE_PORT = int(os.getenv("MEGA_SERVICE_PORT", 7778))
