### ISSUE TITLE
[ChatQnA] AIPC issue MegaService and Add Knowledge Base via HTTP Links issue

### ISSUE THREAD

**Issue by nubiee95** [opea-project/GenAIExamples#494]
I've been setting up the ChatQnA AIPC from the opea-project on my system and have followed the instructions provided here: https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker/aipc

Most microservices are working correctly, but I'm encountering issues with the following two:
- MegaService
- LLM Microservice
- Add Knowledge Base via HTTP Links:

For the LLM Microservice, when I run the following curl command as per the instructions:

However for the LLM Microservice when i following the instruction and try this on the terminal

```
curl http://${host_ip}:9000/v1/chat/completions\
  -X POST \
  -d '{"query":"What is Deep Learning?","max_new_tokens":17,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":true}' \
  -H 'Content-Type: application/json'

```
I receive an "Internal Server Error". The error details are as follows:
```
llm-ollama                    | INFO:     {myIP}:53028 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
llm-ollama                    | ERROR:    Exception in ASGI application
llm-ollama                    | Traceback (most recent call last):
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
llm-ollama                    |     result = await app(  # type: ignore[func-returns-value]
llm-ollama                    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
llm-ollama                    |     return await self.app(scope, receive, send)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
llm-ollama                    |     await super().__call__(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
llm-ollama                    |     await self.middleware_stack(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
llm-ollama                    |     await self.app(scope, receive, _send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
llm-ollama                    |     await self.app(scope, receive, send_wrapper)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
llm-ollama                    |     await self.app(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
llm-ollama                    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-ollama                    |     await app(scope, receive, sender)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
llm-ollama                    |     await self.middleware_stack(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
llm-ollama                    |     await route.handle(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
llm-ollama                    |     await self.app(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
llm-ollama                    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-ollama                    |     await app(scope, receive, sender)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
llm-ollama                    |     response = await func(request)
llm-ollama                    |                ^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
llm-ollama                    |     raw_response = await run_endpoint_function(
llm-ollama                    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
llm-ollama                    |     return await run_in_threadpool(dependant.call, **values)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
llm-ollama                    |     return await anyio.to_thread.run_sync(func, *args)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
llm-ollama                    |     return await get_async_backend().run_sync_in_worker_thread(
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
llm-ollama                    |     return await future
llm-ollama                    |            ^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
llm-ollama                    |     result = context.run(func, *args)
llm-ollama                    |              ^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 582, in wrapper
llm-ollama                    |     raise e
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 579, in wrapper
llm-ollama                    |     function_result = run_container["context"].run(func, *args, **kwargs)
llm-ollama                    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/comps/llms/text-generation/ollama/llm.py", line 22, in llm_generate
llm-ollama                    |     ollama = Ollama(
llm-ollama                    |              ^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
llm-ollama                    |     raise validation_error
llm-ollama                    | pydantic.v1.error_wrappers.ValidationError: 1 validation error for Ollama
llm-ollama                    | model
llm-ollama                    |   none is not an allowed value (type=type_error.none.not_allowed)

```
I was able to resolve this issue by specifying the model in the request:
```
curl http://{myIP}:9000/v1/chat/completions\
  -X POST \
  -d '{"model": "llama3","query":"What is Deep Learning?","max_new_tokens":17,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":true}' \
  -H 'Content-Type: application/json'
```

When i try for MegaService using the curl command following the instruction:
```
curl http://${host_ip}:8888/v1/chatqna -H "Content-Type: application/json" -d '{
     "messages": "What is the revenue of Nike in 2023?", "model": "llama3"
     }'
```
i get an error:
```
llm-ollama                    | INFO:     {myIP}:46984 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
llm-ollama                    | ERROR:    Exception in ASGI application
llm-ollama                    | Traceback (most recent call last):
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
llm-ollama                    |     result = await app(  # type: ignore[func-returns-value]
llm-ollama                    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
llm-ollama                    |     return await self.app(scope, receive, send)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
llm-ollama                    |     await super().__call__(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
llm-ollama                    |     await self.middleware_stack(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
llm-ollama                    |     await self.app(scope, receive, _send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
llm-ollama                    |     await self.app(scope, receive, send_wrapper)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
llm-ollama                    |     await self.app(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
llm-ollama                    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-ollama                    |     await app(scope, receive, sender)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
llm-ollama                    |     await self.middleware_stack(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
llm-ollama                    |     await route.handle(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
llm-ollama                    |     await self.app(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
llm-ollama                    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
llm-ollama                    |     raise exc
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-ollama                    |     await app(scope, receive, sender)
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
llm-ollama                    |     response = await func(request)
llm-ollama                    |                ^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
llm-ollama                    |     raw_response = await run_endpoint_function(
llm-ollama                    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
llm-ollama                    |     return await run_in_threadpool(dependant.call, **values)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
llm-ollama                    |     return await anyio.to_thread.run_sync(func, *args)
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
llm-ollama                    |     return await get_async_backend().run_sync_in_worker_thread(
llm-ollama                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
llm-ollama                    |     return await future
llm-ollama                    |            ^^^^^^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
llm-ollama                    |     result = context.run(func, *args)
llm-ollama                    |              ^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 582, in wrapper
llm-ollama                    |     raise e
llm-ollama                    |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 579, in wrapper
llm-ollama                    |     function_result = run_container["context"].run(func, *args, **kwargs)
llm-ollama                    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-ollama                    |   File "/home/user/comps/llms/text-generation/ollama/llm.py", line 22, in llm_generate
llm-ollama                    |     ollama = Ollama(
llm-ollama                    |              ^^^^^^^
llm-ollama                    |   File "/usr/local/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
llm-ollama                    |     raise validation_error
llm-ollama                    | pydantic.v1.error_wrappers.ValidationError: 1 validation error for Ollama
llm-ollama                    | model
llm-ollama                    |   none is not an allowed value (type=type_error.none.not_allowed)
chatqna-aipc-backend-server   | embedding/MicroService: 200
chatqna-aipc-backend-server   | retriever/MicroService: 200
chatqna-aipc-backend-server   | rerank/MicroService: 200
chatqna-aipc-backend-server   | INFO:     {myIP}:59020 - "POST /v1/chatqna HTTP/1.1" 500 Internal Server Error
chatqna-aipc-backend-server   | ERROR:    Exception in ASGI application
chatqna-aipc-backend-server   | Traceback (most recent call last):
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
chatqna-aipc-backend-server   |     result = await app(  # type: ignore[func-returns-value]
chatqna-aipc-backend-server   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
chatqna-aipc-backend-server   |     return await self.app(scope, receive, send)
chatqna-aipc-backend-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
chatqna-aipc-backend-server   |     await super().__call__(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
chatqna-aipc-backend-server   |     await self.middleware_stack(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
chatqna-aipc-backend-server   |     raise exc
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
chatqna-aipc-backend-server   |     await self.app(scope, receive, _send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
chatqna-aipc-backend-server   |     raise exc
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
chatqna-aipc-backend-server   |     await self.app(scope, receive, send_wrapper)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
chatqna-aipc-backend-server   |     await self.app(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
chatqna-aipc-backend-server   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
chatqna-aipc-backend-server   |     raise exc
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
chatqna-aipc-backend-server   |     await app(scope, receive, sender)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
chatqna-aipc-backend-server   |     await self.middleware_stack(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
chatqna-aipc-backend-server   |     await route.handle(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
chatqna-aipc-backend-server   |     await self.app(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
chatqna-aipc-backend-server   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
chatqna-aipc-backend-server   |     raise exc
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
chatqna-aipc-backend-server   |     await app(scope, receive, sender)
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
chatqna-aipc-backend-server   |     response = await func(request)
chatqna-aipc-backend-server   |                ^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
chatqna-aipc-backend-server   |     raw_response = await run_endpoint_function(
chatqna-aipc-backend-server   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
chatqna-aipc-backend-server   |     return await dependant.call(**values)
chatqna-aipc-backend-server   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/home/user/GenAIComps/comps/cores/mega/gateway.py", line 122, in handle_request
chatqna-aipc-backend-server   |     result_dict, runtime_graph = await self.megaservice.schedule(
chatqna-aipc-backend-server   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 58, in schedule
chatqna-aipc-backend-server   |     response, node = await done_task
chatqna-aipc-backend-server   |                      ^^^^^^^^^^^^^^^
chatqna-aipc-backend-server   |   File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 130, in execute
chatqna-aipc-backend-server   |     endpoint = self.services[downstream[0]].endpoint_path
chatqna-aipc-backend-server   |                              ~~~~~~~~~~^^^
chatqna-aipc-backend-server   | IndexError: list index out of range
```
I'm uncertain if the issue lies with the curl command or the parameters I've entered, as I've been following the instructions provided.

This issue same go for Add Knowledge Base via HTTP Links:
Commend use:
```

curl -X POST "http://{myIP}:6007/v1/dataprep" \
     -H "Content-Type: multipart/form-data" \
     -F 'link_list=["https://opea.dev"]'
```
Error log:
```
dataprep-redis-server         | [ check index existence ] checking <redis.commands.search.Search object at 0x7f279c2c70d0>
dataprep-redis-server         | [ check index existence ] index does not exist: Error 99 connecting to localhost:6379. Cannot assign requested address.
dataprep-redis-server         | [ create index ] creating index file-keys
dataprep-redis-server         | [ create index ] fail to create index file-keys: Error 99 connecting to localhost:6379. Cannot assign requested address.
dataprep-redis-server         | INFO:    {myIP}:59508 - "POST /v1/dataprep HTTP/1.1" 500 Internal Server Error
dataprep-redis-server         | ERROR:    Exception in ASGI application
dataprep-redis-server         | Traceback (most recent call last):
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
dataprep-redis-server         |     result = await app(  # type: ignore[func-returns-value]
dataprep-redis-server         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
dataprep-redis-server         |     return await self.app(scope, receive, send)
dataprep-redis-server         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
dataprep-redis-server         |     await super().__call__(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
dataprep-redis-server         |     await self.middleware_stack(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
dataprep-redis-server         |     raise exc
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
dataprep-redis-server         |     await self.app(scope, receive, _send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
dataprep-redis-server         |     raise exc
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
dataprep-redis-server         |     await self.app(scope, receive, send_wrapper)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
dataprep-redis-server         |     await self.app(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
dataprep-redis-server         |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
dataprep-redis-server         |     raise exc
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
dataprep-redis-server         |     await app(scope, receive, sender)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
dataprep-redis-server         |     await self.middleware_stack(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
dataprep-redis-server         |     await route.handle(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
dataprep-redis-server         |     await self.app(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
dataprep-redis-server         |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
dataprep-redis-server         |     raise exc
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
dataprep-redis-server         |     await app(scope, receive, sender)
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
dataprep-redis-server         |     response = await func(request)
dataprep-redis-server         |                ^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
dataprep-redis-server         |     raw_response = await run_endpoint_function(
dataprep-redis-server         |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
dataprep-redis-server         |     return await dependant.call(**values)
dataprep-redis-server         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 468, in async_wrapper
dataprep-redis-server         |     raise e
dataprep-redis-server         |   File "/home/user/.local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 454, in async_wrapper
dataprep-redis-server         |     function_result = await asyncio.create_task(  # type: ignore[call-arg]
dataprep-redis-server         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         |   File "/home/user/comps/dataprep/redis/langchain/prepare_doc_redis.py", line 272, in ingest_documents
dataprep-redis-server         |     await ingest_link_to_redis(link_list)
dataprep-redis-server         |   File "/home/user/comps/dataprep/redis/langchain/prepare_doc_redis.py", line 203, in ingest_link_to_redis
dataprep-redis-server         |     assert create_index(client)
dataprep-redis-server         |            ^^^^^^^^^^^^^^^^^^^^
dataprep-redis-server         | AssertionError
redis-vector-db               | 9:M 31 Jul 2024 14:07:09.021 * 10000 changes in 60 seconds. Saving...
redis-vector-db               | 9:M 31 Jul 2024 14:07:09.022 * Background saving started by pid 29
redis-vector-db               | 29:C 31 Jul 2024 14:07:09.134 * DB saved on disk
redis-vector-db               | 29:C 31 Jul 2024 14:07:09.135 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
redis-vector-db               | 9:M 31 Jul 2024 14:07:09.223 * Background saving terminated with success

```
System specification:
-cpu: Intel® Core™ Ultra 7 155H × 22
-ram: 64gb
-system: Ubuntu 22.04.4 LTS

**Comment by xiguiw** [comment]
@nubiee95 
Welcome to OPEA.

> llm-ollama                    |   none is not an allowed value (type=type_error.none.not_allowed)

LLM Microservice issue has been fixed. 
Mega are dependency on LLM micro-service.

Would you please update the latest docker image (after v0.9) and have a try?

Thanks
