### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ttrigui** [opea-project/GenAIExamples#818]
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

AI-PC (Please let us know in description)

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

NA

### Description

not able to test LLM Microservice.

### Reproduce steps

Follow steps in https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA/docker_compose/intel/cpu/aipc and when running curl command to test LLM Microservice, you will get a connection error. looking at the log of the docker I got the error below added to Raw log

### Raw log

```shell
Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.1.52
    Uninstalling langchain-core-0.1.52:
      Successfully uninstalled langchain-core-0.1.52
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain 0.1.16 requires langchain-core<0.2.0,>=0.1.42, but you have langchain-core 0.3.0 which is incompatible.
langchain-text-splitters 0.0.2 requires langchain-core<0.3,>=0.1.28, but you have langchain-core 0.3.0 which is incompatible.
langchain-community 0.0.38 requires langchain-core<0.2.0,>=0.1.52, but you have langchain-core 0.3.0 which is incompatible.
Successfully installed langchain-core-0.3.0 langserve-0.3.0
/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/__init__.py:412: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet.         from pydantic.v1 import BaseModel

  from langchain_community.llms.ollama import Ollama
Traceback (most recent call last):
  File "/home/user/comps/llms/text-generation/ollama/langchain/llm.py", line 7, in <module>
    from langchain_community.llms import Ollama
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/__init__.py", line 775, in __getattr__
    return _import_ollama()
           ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/__init__.py", line 412, in _import_ollama
    from langchain_community.llms.ollama import Ollama
  File "/home/user/.local/lib/python3.11/site-packages/langchain_community/llms/ollama.py", line 370, in <module>
    class Ollama(BaseLLM, _OllamaCommon):
  File "/home/user/.local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
  File "/home/user/.local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 583, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 595, in clean_schema
    schema = validate_core_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 570, in validate_core_schema
    return _validate_core_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.config.extra_fields_behavior
  Input should be 'allow', 'forbid' or 'ignore' [type=literal_error, input_value=<Extra.forbid: 'forbid'>, input_type=Extra]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
```

**Comment by lvliang-intel** [comment]
@ttrigui,

The issue is due to the LangChain upgrade to version 0.3.0. I'm working on a fix and will update the PR shortly.

**Comment by ttrigui** [comment]
@lvliang-intel Excellent! I'll wait for the fix, thank you.

**Comment by lvliang-intel** [comment]
@ttrigui,

PR [697](https://github.com/opea-project/GenAIComps/pull/697) fixed this issue.

**Comment by ttrigui** [comment]
excellent! works for me.
