### ISSUE TITLE
[Bug]  chatqna-llm-uservicestatus is CrashLoopBackOff when deploy ProductivitySuite

### ISSUE THREAD

**Issue by shaohef** [opea-project/GenAIExamples#890]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [X] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

latest

### Description

chatqna-llm-uservicestatus is CrashLoopBackOff when deploy ProductivitySuite

### Reproduce steps

follow the official guide

### Raw log

[2024-09-29 19:43:17,114] [    INFO] - Base service - HTTP server setup successful
/home/user/comps/retrievers/redis/langchain/retriever_redis.py:106: LangChainDeprecationWarning: The class `HuggingFaceHubEmbeddings` was deprecated in LangChain 0.2.2 and will be removed
in 1.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from lan
gchain_huggingface import HuggingFaceEndpointEmbeddings`.
  embeddings = HuggingFaceHubEmbeddings(model=tei_embedding_endpoint)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 607, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/comps/retrievers/redis/langchain/retriever_redis.py", line 111, in <module>
    vector_db = Redis(embedding=embeddings, index_name=INDEX_NAME, redis_url=REDIS_URL)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/langchain_community/vectorstores/redis/base.py", line 309, in __init__
    check_redis_module_exist(redis_client, REDIS_REQUIRED_MODULES)
  File "/home/user/.local/lib/python3.11/site-packages/langchain_community/utilities/redis.py", line 55, in check_redis_module_exist
    installed_modules = client.module_list()
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/commands/core.py", line 6250, in module_list
    return self.execute_command("MODULE LIST")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/user/.local/lib/python3.11/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to chatqna-redis-vector-db:6379. Temporary failure in name resolution.
user@host-79402904:/home/user/GenAIExamples/ProductivitySuite/kubernetes/intel/cpu/xeon/manifest$ kubectl apply -f faqgen.yaml
_No response_

**Comment by devpramod** [comment]
Hi @kevinintel 
I observed the same `CrashLoopBackOff` reported here along with the following observations:

1. Initial CrashLoopBackOffs (~1min):
<img width="671" alt="image" src="https://github.com/user-attachments/assets/501abe2d-35f9-4fa6-992f-06baa629d1db">

2. CrashLoopBackOffs after 45 mins of deployment:
<img width="668" alt="image" src="https://github.com/user-attachments/assets/85cd4410-ba29-4c9d-a824-63e2cb079da2">

3. Both codegen and chatqna llm uservice has the same error - 
[error.txt](https://github.com/user-attachments/files/17331540/error.txt)

4. chatqna-retriever-usvc needs HF token to run successfully, which is currently not part of the manifest file

**Comment by XinyaoWa** [comment]
Hi, please rebuild and update the docker images in your K8S cluster with the latest GenAIComps code https://github.com/opea-project/GenAIComps. I get the same error before updating, however after I rebuild and upgrade to the latest images, the error is fixed.

**Comment by joshuayao** [comment]
This issue is inactivate in the past 30 days. Closed.
